Repository opencobra/cobratoolbox, pull requests merged in 2018-08, with the labels that each got.

#1308 Support for Gurobi 8
  docs/source/installation/compatMatrix.rst
  src/base/solvers/changeCobraSolver.m
Labels: ready to merge

#1301 Adding src files of essentialRxns4ModelTutorial
  src/analysis/exploration/essentialRxn4MultipleModels.m
  src/analysis/exploration/plotEssentialRxns.m
Labels: needs testing, ready to merge

#1309 Matlab implementation of CycleFreeFlux
  src/analysis/thermo/thermoFBA/cycleFreeFlux.m
  test/verifiedTests/analysis/testThermo/testCycleFreeFlux.m
Labels: ready to merge

#1303 Added two new functions to Microbiome Modeling Toolbox
  docs/source/modules/analysis/multiSpecies/microbiomeModelingToolbox/additionalAnalysis/index.rst
  docs/source/modules/analysis/multiSpecies/microbiomeModelingToolbox/index.rst
  src/analysis/multiSpecies/microbiomeModelingToolbox/additionalAnalysis/analyseObjectiveShadowPrices.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/additionalAnalysis/calculateReactionAbundance.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/additionalAnalysis/correlateFluxWithTaxonAbundance.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/adaptVMHDietToAGORA.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/createPanModels.m
Labels: do not merge, requires changes

#1313 Cleaning legacy support of gurobi
  src/analysis/topology/FR/checkRankFR.m
  src/analysis/uFBA/buildUFBAmodel.m
  src/base/solvers/changeCobraSolver.m
  src/reconstruction/modelGeneration/stoichConsistency/checkStoichiometricConsistency.m
  test/additionalTests/testFluxConsistency/testFastcc.m
  test/additionalTests/testFluxConsistency/testFluxConsistency.m
  test/additionalTests/testModels/testModelsAlgorithmically.m
  test/verifiedTests/analysis/testComputeFluxSplits/testcomputeFluxSplits.m
  test/verifiedTests/analysis/testDeletionStudy/testDeletionStudy.m
  test/verifiedTests/analysis/testEnumerateOptimal/testenumOptimalSols.m
  test/verifiedTests/analysis/testFBA/testFBA.m
  test/verifiedTests/analysis/testFindBlockedReaction/testFindBlockedReaction.m
  test/verifiedTests/analysis/testGeneMCS/testGeneMCS.m
  test/verifiedTests/analysis/testMultiSpeciesModelling/testCoupleRxnList2Rxn.m
  test/verifiedTests/analysis/testMultiSpeciesModelling/testCreateMultipleSpeciesModel.m
  test/verifiedTests/analysis/testMultiSpeciesModelling/testSimulatePairwiseInteractions.m
  test/verifiedTests/analysis/testSampling/testGpSampler.m
  test/verifiedTests/analysis/testTopology/testFindExtremePathway.m
  test/verifiedTests/analysis/testTopology/testMoieties.m
  test/verifiedTests/base/testCardOpt/testSparseLP.m
  test/verifiedTests/dataIntegration/testMetaboTools/testFluxSplits.m
  test/verifiedTests/design/testOptKnock/testOptKnock.m
  test/verifiedTests/reconstruction/testDetectDeadEnds/testDetectDeadEnds.m
  test/verifiedTests/reconstruction/testFastLeakTest/testFastLeakTest.m
Labels: ready to merge

#1317 Change of verbose flag (doubleGeneDeletion)
  src/analysis/deletion/doubleGeneDeletion.m
Labels: do not merge

#1318 Fix for gurobi path in documentation
  docs/source/installation/solvers.rst
Labels: documentation/tutorials, ready to merge

#1319 Update of build status matrix
  .artenolis.yml
  README.rst
  docs/source/builds.md
Labels: ready to merge

#1320 Moiety code update
  src/analysis/topology/conservedMoieties/identifyConservedMoieties.m
  test/verifiedTests/analysis/testTopology/refData_moieties.mat
Labels: ready to merge

#1321 update of link to mosek license
  docs/source/installation/solvers.rst
Labels: documentation/tutorials, ready to merge
