Repository opencobra/cobratoolbox, pull requests merged in 2018-09, with the labels that each got.

#1302 Improved error message for invalid input
  src/design/OptKnock.m
Labels: do not merge, requires changes

#1324 Regular merge of develop
  src/design/OptKnock.m
Labels: ready to merge

#1328 Single gd fix
  src/analysis/deletion/singleGeneDeletion.m
  test/verifiedTests/analysis/testDeletionStudy/testDeletionStudy.m
Labels: ready to merge

#1332 Update of archive link
  README.rst
Labels: documentation/tutorials

#1334 :bug: Default Values could be wrong
  src/base/io/utilities/createEmptyFields.m
Labels: ready to merge

#1335 Update to createModel
  src/reconstruction/refinement/addMultipleMetabolites.m
  src/reconstruction/refinement/addMultipleReactions.m
  src/reconstruction/refinement/createModel.m
  test/verifiedTests/analysis/testSteadyCom/refData_getMultiSpeciesModelId.mat
  test/verifiedTests/reconstruction/testModelManipulation/testBatchAddition.m
Labels: ready to merge

#1337 Small fix in writeCbmodel
  src/base/io/writeCbModel.m
Labels: ready to merge

#1338 Rxnfix
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/getIndividualSizeName.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/getMappingInfo.m
Labels: ready to merge

#1341 Checking metChEBIID
  src/base/io/utilities/convertOldStyleModel.m
Labels: ready to merge

#1340 adding lost index
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/getMappingInfo.m
Labels: ready to merge
