Repository opencobra/cobratoolbox, pull requests merged in 2018-05, with the labels that each got.

#1189 Conflict resoulution of PR1187
  src/analysis/FBA/optimizeCbModel.m
  src/analysis/relaxedFBA/plotRelaxedFBA.m
  src/analysis/relaxedFBA/relaxFBA_cappedL1.m
  src/analysis/relaxedFBA/relaxedFBA.m
  src/analysis/sparseFBA/sparseFBA.m
  src/analysis/subspaces/subspaceProjection/subspaceProjector.m
  src/base/solvers/cardOpt/sparseLP/optimizeCardinality.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_cappedL1.m
  src/base/solvers/verifyCobraProblem.m
  test/additionalTests/testOptCardinality/testOptCardinality.m
  test/additionalTests/testRelaxedFBA/testRelaxedFBA.m
  test/verifiedTests/analysis/testRelaxedFBA/testRelaxedFBA.m
Labels: ready to merge

#1176 Fix blocked reactions
  src/analysis/exploration/findBlockedReaction.m
Labels: ready to merge

#1192 Expand tests for mgpipe
  src/analysis/exploration/identifyFastBlockedRxns.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/initMgPipe.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/loadUncModels.m
  test/verifiedTests/analysis/testMultiSpeciesModelling/testData_normCoverageReduced.csv
  test/verifiedTests/analysis/testMultiSpeciesModelling/testMgPipe.m
Labels: ready to merge

#1193 Conversion of MD files in guides into RST files.
  .artenolis.yml
  docs/Makefile
  docs/source/guides/documentationGuide.md
  docs/source/guides/documentationGuide.rst
  docs/source/guides/issueGuide.md
  docs/source/guides/issueGuide.rst
  docs/source/guides/styleGuide.md
  docs/source/guides/styleGuide.rst
  docs/source/guides/testGuide.md
  docs/source/guides/testGuide.rst
  src/analysis/thermo/componentContribution/getFormulaAndChargeFromInChI.m
Labels: documentation/tutorials, ready to merge

#1198 Blockfix
  src/analysis/exploration/identifyFastBlockedRxns.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/loadUncModels.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/mgSimResCollect.m
Labels: ready to merge

#1197 Enabled reading in KBase files
  src/base/io/readCbModel.m
Labels: ready to merge

#1202 Incorrect variable name
  src/analysis/FBA/optimizeCbModel.m
Labels: ready to merge

#1203 Allowing user to specify internal reactions
  src/analysis/thermo/thermoFBA/addLoopLawConstraints.m
Labels: ready to merge

#1199 Allowing Opdam 2017 to run on vanilla toolbox
  src/dataIntegration/transcriptomics/INIT/INIT.m
  src/dataIntegration/transcriptomics/MBA/MBA.m
  src/dataIntegration/transcriptomics/createTissueSpecificModel.m
  src/dataIntegration/transcriptomics/iMAT/iMAT.m
  src/reconstruction/modelGeneration/fluxConsistency/findFluxConsistentSubset.m
Labels: ready to merge

#1204 Fixing bug with removal of reaction prior consistency check
  src/dataIntegration/transcriptomics/MBA/MBA.m
Labels: ready to merge

#1205 Update to documentation
  README.rst
  docs/source/installation.rst
  docs/source/installation/requirements.rst
  docs/source/notes/faq.rst
Labels: do not merge, documentation/tutorials, needs review

#1206 Allow template task to be evaluated by the markdown parser.
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready to merge

#1207 Explicit request for launching test suite
  test/testAll.m
Labels: ready to merge

#1210 Ftest
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/getIndividualSizeName.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/loadUncModels.m
  test/verifiedTests/analysis/testMultiSpeciesModelling/testData_normCoverageReduced.csv
  test/verifiedTests/analysis/testMultiSpeciesModelling/testMgPipe.m
Labels: ready to merge

#1217 Added some documentation to createTissueSpecificModel.m
  src/dataIntegration/transcriptomics/createTissueSpecificModel.m
Labels: documentation/tutorials, ready to merge

#1214 Fixing mergeTwoModels
  src/reconstruction/refinement/addGenes.m
  src/reconstruction/refinement/mergeTwoModels.m
  src/reconstruction/refinement/updateFieldOrderForType.m
  test/verifiedTests/reconstruction/testModelManipulation/testMergeTwoModels.m
Labels: ready to merge

#1215 Update of test guide instructions
  docs/source/guides/testGuide.rst
Labels: documentation/tutorials, ready to merge

#1218 Model Name and ID for SBML
  docs/source/notes/COBRAModelFields.md
  src/base/io/definitions/COBRA_structure_fields.csv
  src/base/io/utilities/readSBML.m
  src/base/io/utilities/writeSBML.m
Labels: ready to merge

#1219 fix: Issue 1200, consistent use of osense
  src/base/solvers/solveCobraQP.m
  test/verifiedTests/base/testSolvers/testDuals.m
  test/verifiedTests/base/testSolvers/testSolveCobraQP.m
Labels: ready to merge

#1212 Update writeGDXFromCOBRA.m
  src/base/io/writeGDXFromCOBRA.m
Labels: do not merge

#1223 Adding a test for minimizeModelFlux
  src/analysis/FBA/minimizeModelFlux.m
  test/verifiedTests/analysis/testFBA/createToyModelForMinimizeFlux.m
  test/verifiedTests/analysis/testFBA/testMinimizeModelFlux.m
Labels: ready to merge

#1222 Fixing issues on addMultipleReactions when the model is empty
  src/reconstruction/refinement/addMultipleReactions.m
  test/verifiedTests/reconstruction/testModelManipulation/testBatchAddition.m
Labels: ready to merge
