Repository opencobra/cobratoolbox, pull requests merged in 2018-03, with the labels that each got.

#1099 Osense -> osenseStr
  docs/source/notes/COBRAModelFields.md
  src/analysis/FBA/optimizeCbModel.m
  src/analysis/FVA/fluxVariability.m
  src/analysis/MOMA/MOMA.m
  src/analysis/exploration/getObjectiveSense.m
  src/analysis/mdFBA/buildMDFBAProblem.m
  src/analysis/sampling/ACHR/createHRWarmup.m
  src/base/io/definitions/COBRA_structure_fields.csv
  src/base/io/readCbModel.m
  src/base/io/utilities/convertOldStyleModel.m
  src/base/io/utilities/getDefinedFieldProperties.m
  src/base/io/utilities/model2xls.m
  src/base/io/utilities/readSBML.m
  src/base/io/utilities/writeSBML.m
  src/base/solvers/buildLPproblemFromModel.m
  src/base/solvers/liftModel.m
  src/base/solvers/reformulate.m
  src/base/solvers/solveCobraLP.m
  src/reconstruction/refinement/createModel.m
  test/verifiedTests/analysis/testMOMA/testMOMA.m
  test/verifiedTests/base/testIO/testConvertCNAModelToCbModel.m
  test/verifiedTests/base/testIO/testReadWriteCbModel.m
  test/verifiedTests/base/testIO/testWriteCbModel.m
  test/verifiedTests/reconstruction/testModelManipulation/testExtractMetModel.mat
Labels: do not merge, requires changes

#1122 Update install devTools
  README.rst
  src/base/install/installDevTools.m
Labels: ready to merge

#1123 Update FAQ
  docs/source/notes/FAQ.md
  docs/source/notes/faq.rst
Labels: documentation/tutorials, ready to merge

#1127 Change cobra solver update
  docs/source/notes/faq.rst
  initCobraToolbox.m
  src/analysis/FVA/fluxVariability.m
  src/base/solvers/changeCobraSolver.m
Labels: ready to merge

#1135 All reactions marked as unbalanced if there is exactly one missing formula
  src/reconstruction/modelGeneration/massBalance/checkMassChargeBalance.m
Labels: ready to merge

#1132 Allowing files to fail gracefully
  src/analysis/sparseFBA/sparseFBA.m
  src/analysis/thermo/thermoFBA/addLoopLawConstraints.m
  src/analysis/topology/extremeRays/optimalRays/greedyExtremePoolBasis.m
  src/dataIntegration/fluxomics/C13ConfidenceInterval.m
  src/dataIntegration/fluxomics/c13solver/Combination.m
  src/dataIntegration/fluxomics/c13solver/idv2mdv.m
  src/dataIntegration/fluxomics/compareMultSamp.m
  src/dataIntegration/fluxomics/compareTwoMDVs.m
  src/dataIntegration/fluxomics/compareTwoSamp.m
  src/dataIntegration/fluxomics/generateRandomSample.m
  src/dataIntegration/fluxomics/runHiLoExp.m
  src/dataIntegration/transcriptomics/FASTCORE/fastcore.m
  src/dataIntegration/transcriptomics/GIMME/GIMME.m
  src/design/GetOptGeneSol.m
  src/design/optGene.m
Labels: ready to merge

#1098 Fixed various typos in the genes section of removeFieldEntriesForType.m
  src/reconstruction/refinement/removeFieldEntriesForType.m
  test/verifiedTests/reconstruction/testModelManipulation/testDynamicModelFieldModification.m
Labels: ready to merge

#1144 Hot fixes for develop
  src/analysis/FBA/optimizeCbModel.m
  src/analysis/sparseFBA/sparseFBA.m
  src/base/solvers/solveCobraLP.m
  test/verifiedTests/base/testSolvers/testDualRCostDefinition.m
  test/verifiedTests/base/testSolvers/testLiftModel.m
  test/verifiedTests/reconstruction/testModelGeneration/testTest4HumanFctExt.m
Labels: ready to merge

#1137 Batch add new
  src/base/io/utilities/createEmptyFields.m
  src/reconstruction/refinement/addMetabolite.m
  src/reconstruction/refinement/addMultipleMetabolites.m
  src/reconstruction/refinement/addMultipleReactions.m
  test/verifiedTests/reconstruction/testModelManipulation/testBatchAddition.m
  test/verifiedTests/reconstruction/testModelManipulation/testModelManipulation.m
Labels: ready to merge

#1142 Addition to PR 1098
  src/reconstruction/refinement/GPRLogic/AndNode.m
  src/reconstruction/refinement/GPRLogic/FormulaParser.m
  src/reconstruction/refinement/GPRLogic/LiteralNode.m
  src/reconstruction/refinement/GPRLogic/Node.m
  src/reconstruction/refinement/GPRLogic/OrNode.m
  src/reconstruction/refinement/removeFieldEntriesForType.m
  test/verifiedTests/reconstruction/testGPRLogic/testGPRLogic.m
Labels: ready to merge

#1138 Continuation of PR #1133
  .gitignore
  initCobraToolbox.m
  src/base/install/getFilesInDir.m
  src/base/install/removeGitIgnoredNewFiles.m
  src/base/install/removeTempFiles.m
  src/base/solvers/changeCobraSolver.m
  src/base/solvers/solveCobraMILP.m
  test/testAll.m
  test/verifiedTests/base/testSolvers/testSolveCobraMILP.m
Labels: ready to merge

#1146 sparse optimisation 2
  src/analysis/FBA/optimizeCbModel.m
  src/analysis/relaxedFBA/relaxFBA_cappedL1.m
  src/analysis/relaxedFBA/relaxedFBA.m
  src/base/solvers/cardOpt/sparseLP/optimizeCardinality.m
  src/base/solvers/cardOpt/sparseLP/sparseLP.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_cappedL1.m
  src/base/solvers/solveCobraLP.m
  src/base/solvers/solveCobraQP.m
  test/additionalTests/testRelaxedFBA/testRelaxedFBA.m
  test/verifiedTests/base/testSolvers/testDualRCostDefinition.m
Labels: do not merge, needs review

#1148 Adding the option of parameters for consistency checking
  src/dataIntegration/transcriptomics/createTissueSpecificModel.m
Labels: ready to merge

#1152 Fixed poropagation of arguments into findElementaryMoietyVectors
  src/reconstruction/modelGeneration/massBalance/computeMetFormulae.m
Labels: ready to merge

#1151 Fix TheoretMaxProd Test
  src/design/theoretMaxProd.m
  test/verifiedTests/design/testTheoretMaxProd.m
Labels: ready to merge

#1150 Fix single gene del
  src/analysis/deletion/deleteModelGenes.m
  src/analysis/deletion/doubleGeneDeletion.m
  src/analysis/deletion/singleGeneDeletion.m
  src/analysis/exploration/findMetabolicJunctions.m
  src/analysis/exploration/findSubSysGen.m
  src/analysis/gMCS/GPR2models.m
  src/analysis/gMCS/buildGmatrix.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/pairwiseInteractionModeling/computeRescuedGenes.m
  src/analysis/parsimoniousFBA/pFBA.m
  src/analysis/rumba/normalizePoints.m
  src/design/GDLS.m
  src/design/optGeneFitness.m
  src/design/optGeneFitnessTilt.m
  src/design/simpleOptKnock.m
  src/visualization/metabolicCartography/colorRxnsFromGenes.m
Labels: ready to merge
