Repository opencobra/cobratoolbox, pull requests merged in 2018-06, with the labels that each got.

#1229 [documentation] libSBML 5.17 docu update
  README.rst
Labels: documentation/tutorials, ready to merge

#1232 Removing redundant file
  src/analysis/thermo/componentContribution/getGroupVectorFromInchi.m
Labels: ready to merge

#1233 Changing babel to obabel
  src/analysis/thermo/componentContribution/getInchies.m
  src/analysis/thermo/componentContribution/getKeggpKas.m
  src/analysis/thermo/groupContribution/modelMetabolitesToSDF.m
  src/analysis/thermo/inchi/sdf2inchi.m
  src/analysis/thermo/protons/assignpKasToSpecies.m
  src/analysis/thermo/protons/inchi2mol.m
  src/analysis/thermo/vonBertalanffy/initVonBertalanffy.m
  src/reconstruction/modelGeneration/massBalance/basicPhysicochemicalData/getMolecularMass.m
Labels: ready to merge

#1236 Fix calculation of failed tests in testAll
  docs/source/installation/compatMatrix.md
  src/base/solvers/isCompatible.m
  test/testAll.m
  test/verifiedTests/base/testSolvers/testIsCompatible.m
Labels: ready to merge

#1234 Some speedup for generateRules
  src/base/parseGPR.m
  src/base/preparseGPR.m
  src/reconstruction/refinement/generateRules.m
  test/verifiedTests/reconstruction/testModelManipulation/testGenerateRules.m
Labels: ready to merge

#1242 Added informative outputs to solution struct
  src/base/solvers/cardOpt/sparseLP/sparseLP_SCAD.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_cappedL1.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_exp.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_l1.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_log.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_lpNegative.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_lpPositive.m
Labels: ready to merge

#1241 Update .gitignore file
  .gitignore
Labels: ready to merge

#1245 Regular merge of develop
  .gitignore
  README.rst
  docs/source/installation/compatMatrix.md
  src/analysis/exploration/findSubSysGen.m
  src/analysis/exploration/findSubSystemsFromGenes.m
  src/analysis/thermo/componentContribution/getGroupVectorFromInchi.m
  src/analysis/thermo/componentContribution/getInchies.m
  src/analysis/thermo/componentContribution/getKeggpKas.m
  src/analysis/thermo/groupContribution/modelMetabolitesToSDF.m
  src/analysis/thermo/inchi/sdf2inchi.m
  src/analysis/thermo/protons/assignpKasToSpecies.m
  src/analysis/thermo/protons/inchi2mol.m
  src/analysis/thermo/vonBertalanffy/initVonBertalanffy.m
  src/base/parseGPR.m
  src/base/preparseGPR.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_SCAD.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_cappedL1.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_exp.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_l1.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_log.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_lpNegative.m
  src/base/solvers/cardOpt/sparseLP/sparseLP_lpPositive.m
  src/base/solvers/isCompatible.m
  src/reconstruction/modelGeneration/massBalance/basicPhysicochemicalData/getMolecularMass.m
  src/reconstruction/refinement/addDemandReaction.m
  src/reconstruction/refinement/addExchangeRxn.m
  src/reconstruction/refinement/addMultipleReactions.m
  src/reconstruction/refinement/generateRules.m
  test/testAll.m
  test/verifiedTests/analysis/testExploration/testFindSubSystemsFromGenes.m
  test/verifiedTests/base/testSolvers/testIsCompatible.m
  test/verifiedTests/reconstruction/testModelManipulation/testBatchAddition.m
  test/verifiedTests/reconstruction/testModelManipulation/testGenerateRules.m
Labels: ready to merge

#1248 fixing SBOTerm property definition
  src/base/io/definitions/COBRA_structure_fields.csv
Labels: ready to merge

#1246 Functionality to allow searching a model
  src/analysis/exploration/findMatchingFieldEntries.m
  src/analysis/exploration/searchModel.m
  src/base/io/utilities/SBML/getBioQualifiers.m
  src/base/io/utilities/SBML/makeSBMLAnnotationString.m
  src/base/utilities/calcDist.m
  test/verifiedTests/analysis/testExploration/testSearchModel.m
Labels: ready to merge

#1238 Fix biomassPrecursorCheck
  src/analysis/exploration/biomassPrecursorCheck.m
  test/verifiedTests/analysis/testBiomassPrecursorCheck/testBiomassPrecursorCheck.m
Labels: ready to merge

#1250 Fixing bug with caps mismatch with printLevel
  src/base/solvers/liftModel.m
  src/base/solvers/reformulate.m
  src/dataIntegration/transcriptomics/FASTCORE/fastcore.m
  src/dataIntegration/transcriptomics/createTissueSpecificModel.m
Labels: ready to merge

#1256 Moving ReconMap test until API fixed
  test/additionalTests/testReconMap/testReconMap.m
Labels: ready to merge

#1254 Changing parameters
  src/analysis/sampling/calcSampleDifference.m
Labels: ready to merge

#1255 [external] Modifications to colorful spy plot
  external/spyc/spyc.m
Labels: ready to merge

#1237 Curl on cluster
  initCobraToolbox.m
Labels: do not merge, needs review, requires changes

#1257 Bugfix, compatibility with maxCardinality
  src/reconstruction/modelGeneration/stoichConsistency/checkStoichiometricConsistency.m
Labels: ready to merge

#1265 Fixing bug with mCADRE creating non-unique values, which
  external/mCADRE/mCADRE.m
Labels: ready to merge

#1269 [documentation] Added Note on use of addReaction vs addMultipleReactions
  src/reconstruction/refinement/addReaction.m
Labels: ready to merge

#1268 Fixing bug in generateRules caused by #1234
  src/reconstruction/refinement/addGenes.m
  src/reconstruction/refinement/generateRules.m
  test/verifiedTests/reconstruction/testModelManipulation/testGenerateRules.m
Labels: ready to merge

#1274 Adding a option to check for a website to prepareTest
  src/base/install/prepareTest.m
  test/verifiedTests/base/testIO/testLoadBiGGModel.m
  test/verifiedTests/visualization/testReconMap/testReconMap.m
Labels: ready to merge

#1271 Adding a flag to allow a toolbox update to be optional
  initCobraToolbox.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/adaptVMHDietToAGORA.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/microbiotaModelSimulator.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/pairwiseInteractionModeling/computeParetoOptimality.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/pairwiseInteractionModeling/computeRescuedGenes.m
  src/base/install/installDevTools.m
  src/base/io/utilities/generateFieldDescriptionFile.m
  src/base/io/utilities/getDistributedModel.m
  src/base/io/utilities/getDistributedModelFolder.m
  src/base/solvers/changeCobraSolver.m
  src/base/solvers/getAvailableSolversByType.m
  src/base/solvers/getCobraSolverVersion.m
Labels: ready to merge

#1266 Miriam annotation
  src/analysis/exploration/getMIRIAMAnnotations.m
  src/base/io/definitions/COBRA_structure_fields.csv
  src/base/io/definitions/getAnnotationFieldName.m
  src/base/io/definitions/getRegisteredDatabases.m
  src/base/io/utilities/SBML/getBioQualifiers.m
  src/base/io/utilities/SBML/mapAnnotationsToFields.m
  src/base/io/utilities/getDatabaseMappings.m
  src/base/io/utilities/getDefinedFieldProperties.m
  src/reconstruction/refinement/addMIRIAMAnnotations.m
  test/verifiedTests/base/testIO/testUtilities/testGetDatabaseMappings.m
  test/verifiedTests/reconstruction/testModelManipulation/testMIRIAMAnnotation.m
Labels: ready to merge

#1278 Hot fix: Use curl instead of webread
  src/base/install/prepareTest.m
Labels: ready to merge, unix

#1280 Update to style guide
  docs/source/guides/styleGuide.rst
Labels: documentation/tutorials, ready to merge

#1273 Fix for issue 1267 - sequential version of fastFVA
  src/analysis/FVA/fastFVA/fastFVA.m
  test/verifiedTests/analysis/testFVA/testFastFVA.m
Labels: ready to merge

#1279 Continuation of PR 1276
  initCobraToolbox.m
Labels: ready to merge

#1281 Continuation of #1277
  docs/source/installation/requirements.rst
  docs/source/notes/faq.rst
  src/base/install/prepareTest.m
  test/verifiedTests/base/testIO/testListBiGGModels.m
Labels: ready to merge

#1282 Combination of PR 1272 and PR 1275
  initCobraToolbox.m
  src/base/solvers/changeCobraSolver.m
  src/base/solvers/getCobraSolverParams.m
  src/base/solvers/getCobraSolverParamsOptionsForType.m
  src/base/solvers/parseSolverParameters.m
  src/base/solvers/solveCobraLP.m
  src/base/solvers/solveCobraMILP.m
  src/base/solvers/solveCobraMIQP.m
  src/base/solvers/solveCobraNLP.m
  src/base/solvers/solveCobraQP.m
  src/base/utilities/updateStructData.m
  src/reconstruction/modelGeneration/massBalance/computeMetFormulae.m
  test/verifiedTests/base/testSolvers/testSolveCobraLP.m
  test/verifiedTests/base/testSolvers/testSolveCobraQP.m
Labels: ready to merge

#1285 Better instructions for updateCobraToolbox
  docs/source/notes/faq.rst
  src/base/install/updateCobraToolbox.m
Labels: documentation/tutorials, ready to merge
