Repository opencobra/cobratoolbox, pull requests merged in 2018-04, with the labels that each got.

#1155 [documentation] Add Remark how to clean old cobra toolboxes
  docs/source/notes/faq.rst
Labels: ready to merge

#1153 butterfly v1
  src/analysis/MOMA/MOMA.m
  src/base/solvers/getCobraSolverParams.m
  src/base/solvers/solveCobraQP.m
  src/reconstruction/modelGeneration/massBalance/findSExRxnInd.m
Labels: ready to merge

#1158 Parse sbml notes improvements
  src/base/io/utilities/parseSBMLNotesField.m
  src/base/io/utilities/readSBML.m
Labels: ready to merge

#1157 Continuation of PR 1102
  docs/source/guides/testGuide.md
  docs/source/guides/testTemplate.m
  initCobraToolbox.m
  src/analysis/FVA/fluxVariability.m
  src/base/install/getFilesInDir.m
  src/base/install/getIgnoredFiles.m
  src/base/install/prepareTest.m
  src/base/install/removeTempFiles.m
  src/base/solvers/CPLEXParamSet.m
  src/base/solvers/buildLPproblemFromModel.m
  src/base/solvers/changeCobraSolver.m
  src/base/solvers/checkSolFeas.m
  src/base/solvers/getAvailableSolversByType.m
  src/design/singleProductionEnvelope.m
  test/runScriptFile.m
  test/runTestSuite.m
  test/testAll.m
  test/verifiedTests/analysis/testConnectedComponents/testConnectedComponents.m
  test/verifiedTests/analysis/testFEA/testFEA.m
  test/verifiedTests/analysis/testFVA/testFastFVA.m
  test/verifiedTests/analysis/testNullspace/testNullspace.m
  test/verifiedTests/analysis/testRank/testRank.m
  test/verifiedTests/analysis/testSampling/testSampleCbModel.m
  test/verifiedTests/analysis/testSubspaces/testMinSpan.m
  test/verifiedTests/analysis/testTopology/testExtremePathways.m
  test/verifiedTests/analysis/testTopology/testMoieties.m
  test/verifiedTests/analysis/testuFBA/testuFBA.m
  test/verifiedTests/base/testIO/testLoadBiGGModel.m
  test/verifiedTests/base/testIO/testReadSBML.m
  test/verifiedTests/base/testSolvers/outputSummary.m
  test/verifiedTests/base/testSolvers/testDualRCostDefinition.m
  test/verifiedTests/base/testSolvers/testIsCompatible.m
  test/verifiedTests/base/testSolvers/testOptimizeCbModelNLP.m
  test/verifiedTests/base/testSolvers/testSolveCobraLP.m
  test/verifiedTests/base/testSolvers/testSolveCobraMILP.m
  test/verifiedTests/base/testSolvers/testSolveCobraMIQP.m
  test/verifiedTests/base/testSolvers/testSolveCobraNLP.m
  test/verifiedTests/dataIntegration/testFitC13Data/testFitC13Data.m
  test/verifiedTests/design/testOptGene.m
  test/verifiedTests/visualization/testPaint4Net/testPaint4Net.m
Labels: ready to merge

#1147 Return of duals and reduced costs from solveCobraQP
  src/analysis/MOMA/MOMA.m
  src/base/solvers/solveCobraCPLEX.m
  src/base/solvers/solveCobraQP.m
  test/verifiedTests/analysis/testMOMA/testMOMA.m
  test/verifiedTests/base/testSolvers/testDuals.m
Labels: ready to merge

#1161 Cnf conversion
  src/reconstruction/refinement/GPRLogic/AndNode.m
  src/reconstruction/refinement/GPRLogic/LiteralNode.m
  src/reconstruction/refinement/GPRLogic/Node.m
  src/reconstruction/refinement/GPRLogic/OrNode.m
  src/reconstruction/refinement/GPRLogic/combineChildren.m
  test/verifiedTests/reconstruction/testGPRLogic/testGPRLogic.m
Labels: ready to merge

#1160 Documentation Update for the Reconstruction Folder
  src/reconstruction/refinement/addGenes.m
  src/reconstruction/refinement/addMetabolite.m
  src/reconstruction/refinement/addMultipleMetabolites.m
  src/reconstruction/refinement/addMultipleReactions.m
  src/reconstruction/refinement/addReactionGEM.m
  src/reconstruction/refinement/addSubSystemsToReactions.m
  src/reconstruction/refinement/changeRxnMets.m
  src/reconstruction/refinement/convertToIrreversible.m
  src/reconstruction/refinement/createModel.m
  src/reconstruction/refinement/extendModelFieldsForType.m
  src/reconstruction/refinement/getModelFieldsForType.m
  src/reconstruction/refinement/mergeModelFieldPositions.m
  src/reconstruction/refinement/removeRxns.m
  src/reconstruction/refinement/removeSubSystemsFromRxns.m
  src/reconstruction/refinement/setRxnSubSystems.m
  src/reconstruction/refinement/updateGenes.m
Labels: documentation/tutorials, ready to merge

#1165 Test suit fixes
  docs/source/guides/testGuide.md
  docs/source/notes/faq.rst
  src/analysis/FVA/fluxVariability.m
  src/analysis/multiSpecies/SteadyCom/subroutines/SteadyComFVAgr.m
  src/base/install/prepareTest.m
  src/base/solvers/getAvailableSolversByType.m
  src/base/solvers/isCompatible.m
  src/base/solvers/solveCobraLP.m
  src/base/utilities/clearGlobal.m
  src/base/utilities/getEnvironment.m
  src/base/utilities/getGlobalValue.m
  src/base/utilities/restoreEnvironment.m
  src/base/utilities/setGlobal.m
  test/runScriptFile.m
  test/runTestSuite.m
  test/verifiedTests/analysis/testSteadyCom/testSteadyCom.m
  test/verifiedTests/base/testIO/testLoadBiGGModel.m
  test/verifiedTests/base/testIO/testReadSBML.m
  test/verifiedTests/base/testSolvers/testOptimizeTwoCbModels.m
  test/verifiedTests/base/testSolvers/testSolveCobraQP.m
  test/verifiedTests/design/testAnalyzeGCdesign.m
  test/verifiedTests/reconstruction/testComputeMetFormulae/testComputeMetFormulae.m
  test/verifiedTests/visualization/testPaint4Net/testPaint4Net.m
Labels: do not merge, needs review

#1167 Add an option to exclude Solvers for Tests
  docs/source/guides/testGuide.md
  src/base/install/prepareTest.m
Labels: ready to merge

#1168 Setting Proper Test requirements
  test/verifiedTests/analysis/testfindMIIS/testfindMIIS.m
  test/verifiedTests/base/testSolvers/testIsCompatible.m
  test/verifiedTests/base/testSolvers/testSolveCobraCPLEX.m
  test/verifiedTests/base/testSolvers/testTuneParam.m
  test/verifiedTests/design/testOptForce/testOptForce.m
  test/verifiedTests/design/testOptForce/validateOptForceSol.m
  test/verifiedTests/reconstruction/testModelGeneration/testTest4HumanFctExt.m
Labels: ready to merge

#1169 Corrected Path in xlwrite
  external/xlwrite/setupxlwrite.m
Labels: ready to merge

#1172 Fix installation of portable git
  src/base/install/portableGitSetup.m
Labels: ready to merge, windows

#1170 Test for Microbiome Toolbox (initialization)
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/detectOutput.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/initMgPipe.m
  test/verifiedTests/analysis/testMultiSpeciesModelling/testMgPipe.m
Labels: ready to merge

#1175 Thermo core 2
  external/venn/license.txt
  external/venn/venn.m
  src/dataIntegration/transcriptomics/FASTCORE/fastcore.m
Labels: ready to merge

#1177 Update to restore Environment
  src/analysis/FVA/fluxVariability.m
  src/analysis/multiSpecies/SteadyCom/subroutines/SteadyComFVAgr.m
  src/base/utilities/restoreEnvironment.m
Labels: ready to merge

#1166 New version of gMCS using CPLEX
  src/analysis/gMCS/GPR2models.m
  src/analysis/gMCS/buildGmatrix.m
  src/analysis/gMCS/calculateGeneMCS.m
  src/analysis/gMCS/calculateMCS.m
  test/verifiedTests/analysis/testGeneMCS/testGeneMCS.m
Labels: ready to merge

#1171 Test for relaxFBA
  src/analysis/relaxedFBA/relaxedFBA.m
  test/additionalTests/testRelaxedFBA/testRelaxedFBA.m
  test/verifiedTests/analysis/testRelaxedFBA/testRelaxedFBA.m
Labels: ready to merge

#1179 Fixnew
  src/analysis/exploration/identifyFastBlockedRxns.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/fastSetupCreator.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/loadUncModels.m
  src/analysis/multiSpecies/microbiomeModelingToolbox/mgPipe/microbiotaModelSimulator.m
Labels: ready to merge

#1181 Fix for rxnConfidenceScores
  src/base/io/utilities/xls2model.m
Labels: ready to merge

#1182 Update BiGG Test to skip if no connection to BiGG possible
  test/verifiedTests/base/testIO/testLoadBiGGModel.m
Labels: ready to merge

#1186 Correction for verifyFunctionError
  docs/source/guides/testTemplate.m
  test/verifiedTests/analysis/testMultiSpeciesModelling/testJoinModelsPairwiseFromList.m
  test/verifiedTests/analysis/testMultiSpeciesModelling/testMgPipe.m
  test/verifiedTests/analysis/testPrint/testPrintGPRForRxns.m
  test/verifiedTests/analysis/testTopology/testExtremePathways.m
  test/verifiedTests/base/testInstall/testAddKeyToKnownHosts.m
  test/verifiedTests/reconstruction/testModelManipulation/testBatchAddition.m
  test/verifiedTests/reconstruction/testModelManipulation/testModelManipulation.m
  test/verifyCobraFunctionError.m
Labels: ready to merge

#1185 Adaption of FVA to unbounded systems
  src/analysis/FVA/fluxVariability.m
  src/base/solvers/solveCobraLP.m
Labels: ready to merge
